### ISSUE TITLE
cannot start debugging because the debug target is missing

### ISSUE THREAD

**Issue by zawawimanja** [bretgourdie/nezzy-bird#1]
cannot start debugging because the debug target is missing bin\DesktopGL\AnyCPU\Debug\NezzyBird.exe is missing.

**Comment by bretgourdie** [comment]
Sounds like you're missing MonoGame or the full Nez. It's hard to tell from this error.

Nez is kind of weird because, at least in the version I got, certain files required for compilation are in the .gitignore, so simply pulling down the repo isn't enough.

**Comment by bretgourdie** [comment]
I've updated to a newer version of Nez which fixes the .gitignore issue. There should be no issues getting an executable once MonoGame is installed.
